### ISSUE TITLE
Possibility to match IPs with wildcards?

### ISSUE THREAD

**Issue by darthnorman** [jweiland-net/jwauth#2]
It looks like wildcards are not supported, matching will fail, could you add wildcard support?
Example: I want to login all users from 172.22.*.*

**Comment by froemken** [comment]
Hello @darthnorman 

I have just looked into the code and I'm using GeneralUtility:cmpIP of TYPO3 Core API which can work with * by default. So please check if REMOTE_ADDR really matches the correct IP address. But maybe you have an IPv6 address. In that case please use 0 as mask like comment in cmpIPv6() `// Special case; /0 is an allowed mask - equals a wildcard`

**Comment by froemken** [comment]
Hello @darthnorman 

I have just found the problem and released version 2.1.0
Thank you for your help

Stefan
